### ISSUE TITLE
Missing "version" in package.json

### ISSUE THREAD

**Issue by Dom-nik** [JuanCarniglia/area3d_vis#1]
Hello,
"version" field is missing in package.json, which causes a fatal error when starting Kibana.

It should look like this:
`"version": "5.0.1"`

**Comment by JuanCarniglia** [comment]
I added "kibana" as the version (right now) as the other core plugins in Kibana have.

Maybe with that it should work? Can you please test it on your local package.json?

Thanks for the feedback!

**Comment by Dom-nik** [comment]
Most of the community plugins contain a version that matches the Kibana version they are designed for (e.g. `"version": "5.0.1"`), but it seems that your solution works fine. 

I'm no expert on plugin development, but this looks like a smart workaround to prevent Kibana from checking version compatibility of the plugins, which is quite a nice thing, I guess, if we take into account that this check breaks all plugins after Kibana upgrade: https://discuss.elastic.co/t/plugins-break-after-upgrade-5-0-0-5-0-1/66401 :]

Please check https://github.com/JuanCarniglia/area3d_vis/issues/2 to view my opinion o installing you plugin as a core plugin ;]
