### ISSUE TITLE
Missing installation instructions

### ISSUE THREAD

**Issue by Dom-nik** [JuanCarniglia/area3d_vis#2]
I think it's worth to add a couple of lines with install instructions to README.

I tried:
```bash
git clone https://github.com/JuanCarniglia/area3d_vis
cd area3d_vis
npm install
```
and it seems to work fine.

**Comment by JuanCarniglia** [comment]
Added! Thanks!

**Comment by Dom-nik** [comment]
Thanks for fast reaction!
However, I think that you shouldn't install your plugin as a core one (in $KIBANA_HOME/src/core_plugins), but stick with the regular plugins directory ($KIBANA_HOME/plugins/) :]
