### ISSUE TITLE
Installation issue: Invalid version Kibana

### ISSUE THREAD

**Issue by pg2455** [JuanCarniglia/area3d_vis#4]
I am installing this plugin and have tried two versions of Kibana so far. Both of them ended with the same error which seems to be very confusing. I tried Kibana-5.0.0 and Kibana-5.0.1
The error that I got is: 
```
npm WARN Invalid version: "kibana"
npm WARN area3d_vis No description
npm WARN area3d_vis No repository field.
npm WARN area3d_vis No README data
npm WARN area3d_vis No license field.
```

**Comment by virusu** [comment]
Hey @prateekpg2455. Just change the value of the "version" tag on the package.json to your Kibana version and you're done.

**Comment by khelmrab** [comment]
hey @virusu @prateekpg2455  , i have the same probleme 
the error that i git is:
`npm WARN kibana@5.4.0 No license field.`
and i have same value of the "version" on the package.json with my Kibana version .
and it's not working !
